apiVersion: apps/v1
kind:       Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name:  zookeeper
          image: arti.dev.cray.com/third-party-docker-stable-local/confluentinc/cp-zookeeper:6.1.1
          ports:
            - containerPort: 2181
          env:
            - name:  ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name:  ZOOKEEPER_TICK_TIME
              value: "2000"
---
apiVersion: v1
kind:       Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port:     2181
      protocol: TCP
      nodePort: 32181
  selector:
    app: zookeeper
  type: NodePort