// +build !ignore_autogenerated

// Code generated by operator-sdk-v0.15.2-x86_64-apple-darwin. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TRSWorker) DeepCopyInto(out *TRSWorker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TRSWorker.
func (in *TRSWorker) DeepCopy() *TRSWorker {
	if in == nil {
		return nil
	}
	out := new(TRSWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TRSWorker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TRSWorkerList) DeepCopyInto(out *TRSWorkerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TRSWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TRSWorkerList.
func (in *TRSWorkerList) DeepCopy() *TRSWorkerList {
	if in == nil {
		return nil
	}
	out := new(TRSWorkerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TRSWorkerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TRSWorkerSpec) DeepCopyInto(out *TRSWorkerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TRSWorkerSpec.
func (in *TRSWorkerSpec) DeepCopy() *TRSWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(TRSWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TRSWorkerStatus) DeepCopyInto(out *TRSWorkerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TRSWorkerStatus.
func (in *TRSWorkerStatus) DeepCopy() *TRSWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(TRSWorkerStatus)
	in.DeepCopyInto(out)
	return out
}
