name: Build and Publish opeartor-sdk Docker Image
on:
  - push # Perform a build of the contents from the branch
  - pull_request # Perform a build after merging with the target branch
  - workflow_dispatch
jobs:
  build_and_release:
    uses: Cray-HPE/hms-build-image-workflows/.github/workflows/build_and_release_image.yaml@v2
    with:
      image-name: cray-trs-operator-sdk
      docker-build-file: operator-sdk/Dockerfile
      docker-build-context: operator-sdk
      enable-pr-comment: true
    secrets: inherit
